/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstantesIndexRouteImport } from './routes/estantes.index'
import { Route as LivrosBookIdRouteImport } from './routes/livros.$bookId'
import { Route as EstantesShelfIdRouteImport } from './routes/estantes.$shelfId'
import { Route as PaginasPageIdIndexRouteImport } from './routes/paginas.$pageId.index'
import { Route as PaginasPageIdEditarRouteImport } from './routes/paginas.$pageId.editar'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstantesIndexRoute = EstantesIndexRouteImport.update({
  id: '/estantes/',
  path: '/estantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosBookIdRoute = LivrosBookIdRouteImport.update({
  id: '/livros/$bookId',
  path: '/livros/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstantesShelfIdRoute = EstantesShelfIdRouteImport.update({
  id: '/estantes/$shelfId',
  path: '/estantes/$shelfId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginasPageIdIndexRoute = PaginasPageIdIndexRouteImport.update({
  id: '/paginas/$pageId/',
  path: '/paginas/$pageId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginasPageIdEditarRoute = PaginasPageIdEditarRouteImport.update({
  id: '/paginas/$pageId/editar',
  path: '/paginas/$pageId/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/estantes/$shelfId': typeof EstantesShelfIdRoute
  '/livros/$bookId': typeof LivrosBookIdRoute
  '/estantes/': typeof EstantesIndexRoute
  '/paginas/$pageId/editar': typeof PaginasPageIdEditarRoute
  '/paginas/$pageId/': typeof PaginasPageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/estantes/$shelfId': typeof EstantesShelfIdRoute
  '/livros/$bookId': typeof LivrosBookIdRoute
  '/estantes': typeof EstantesIndexRoute
  '/paginas/$pageId/editar': typeof PaginasPageIdEditarRoute
  '/paginas/$pageId': typeof PaginasPageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/estantes/$shelfId': typeof EstantesShelfIdRoute
  '/livros/$bookId': typeof LivrosBookIdRoute
  '/estantes/': typeof EstantesIndexRoute
  '/paginas/$pageId/editar': typeof PaginasPageIdEditarRoute
  '/paginas/$pageId/': typeof PaginasPageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/reset-password'
    | '/estantes/$shelfId'
    | '/livros/$bookId'
    | '/estantes/'
    | '/paginas/$pageId/editar'
    | '/paginas/$pageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/reset-password'
    | '/estantes/$shelfId'
    | '/livros/$bookId'
    | '/estantes'
    | '/paginas/$pageId/editar'
    | '/paginas/$pageId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/busca'
    | '/reset-password'
    | '/estantes/$shelfId'
    | '/livros/$bookId'
    | '/estantes/'
    | '/paginas/$pageId/editar'
    | '/paginas/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EstantesShelfIdRoute: typeof EstantesShelfIdRoute
  LivrosBookIdRoute: typeof LivrosBookIdRoute
  EstantesIndexRoute: typeof EstantesIndexRoute
  PaginasPageIdEditarRoute: typeof PaginasPageIdEditarRoute
  PaginasPageIdIndexRoute: typeof PaginasPageIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estantes/': {
      id: '/estantes/'
      path: '/estantes'
      fullPath: '/estantes/'
      preLoaderRoute: typeof EstantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/$bookId': {
      id: '/livros/$bookId'
      path: '/livros/$bookId'
      fullPath: '/livros/$bookId'
      preLoaderRoute: typeof LivrosBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estantes/$shelfId': {
      id: '/estantes/$shelfId'
      path: '/estantes/$shelfId'
      fullPath: '/estantes/$shelfId'
      preLoaderRoute: typeof EstantesShelfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginas/$pageId/': {
      id: '/paginas/$pageId/'
      path: '/paginas/$pageId'
      fullPath: '/paginas/$pageId/'
      preLoaderRoute: typeof PaginasPageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginas/$pageId/editar': {
      id: '/paginas/$pageId/editar'
      path: '/paginas/$pageId/editar'
      fullPath: '/paginas/$pageId/editar'
      preLoaderRoute: typeof PaginasPageIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EstantesShelfIdRoute: EstantesShelfIdRoute,
  LivrosBookIdRoute: LivrosBookIdRoute,
  EstantesIndexRoute: EstantesIndexRoute,
  PaginasPageIdEditarRoute: PaginasPageIdEditarRoute,
  PaginasPageIdIndexRoute: PaginasPageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
