/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as EstantesRouteImport } from './routes/estantes'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaginasPageIdRouteImport } from './routes/paginas.$pageId'
import { Route as LivrosBookIdRouteImport } from './routes/livros.$bookId'
import { Route as EstantesShelfIdRouteImport } from './routes/estantes.$shelfId'
import { Route as PaginasPageIdEditarRouteImport } from './routes/paginas.$pageId.editar'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EstantesRoute = EstantesRouteImport.update({
  id: '/estantes',
  path: '/estantes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginasPageIdRoute = PaginasPageIdRouteImport.update({
  id: '/paginas/$pageId',
  path: '/paginas/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosBookIdRoute = LivrosBookIdRouteImport.update({
  id: '/livros/$bookId',
  path: '/livros/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstantesShelfIdRoute = EstantesShelfIdRouteImport.update({
  id: '/$shelfId',
  path: '/$shelfId',
  getParentRoute: () => EstantesRoute,
} as any)
const PaginasPageIdEditarRoute = PaginasPageIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => PaginasPageIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/estantes': typeof EstantesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/estantes/$shelfId': typeof EstantesShelfIdRoute
  '/livros/$bookId': typeof LivrosBookIdRoute
  '/paginas/$pageId': typeof PaginasPageIdRouteWithChildren
  '/paginas/$pageId/editar': typeof PaginasPageIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/estantes': typeof EstantesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/estantes/$shelfId': typeof EstantesShelfIdRoute
  '/livros/$bookId': typeof LivrosBookIdRoute
  '/paginas/$pageId': typeof PaginasPageIdRouteWithChildren
  '/paginas/$pageId/editar': typeof PaginasPageIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/estantes': typeof EstantesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/estantes/$shelfId': typeof EstantesShelfIdRoute
  '/livros/$bookId': typeof LivrosBookIdRoute
  '/paginas/$pageId': typeof PaginasPageIdRouteWithChildren
  '/paginas/$pageId/editar': typeof PaginasPageIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/estantes'
    | '/reset-password'
    | '/estantes/$shelfId'
    | '/livros/$bookId'
    | '/paginas/$pageId'
    | '/paginas/$pageId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/estantes'
    | '/reset-password'
    | '/estantes/$shelfId'
    | '/livros/$bookId'
    | '/paginas/$pageId'
    | '/paginas/$pageId/editar'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/busca'
    | '/estantes'
    | '/reset-password'
    | '/estantes/$shelfId'
    | '/livros/$bookId'
    | '/paginas/$pageId'
    | '/paginas/$pageId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  EstantesRoute: typeof EstantesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  LivrosBookIdRoute: typeof LivrosBookIdRoute
  PaginasPageIdRoute: typeof PaginasPageIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estantes': {
      id: '/estantes'
      path: '/estantes'
      fullPath: '/estantes'
      preLoaderRoute: typeof EstantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginas/$pageId': {
      id: '/paginas/$pageId'
      path: '/paginas/$pageId'
      fullPath: '/paginas/$pageId'
      preLoaderRoute: typeof PaginasPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/$bookId': {
      id: '/livros/$bookId'
      path: '/livros/$bookId'
      fullPath: '/livros/$bookId'
      preLoaderRoute: typeof LivrosBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estantes/$shelfId': {
      id: '/estantes/$shelfId'
      path: '/$shelfId'
      fullPath: '/estantes/$shelfId'
      preLoaderRoute: typeof EstantesShelfIdRouteImport
      parentRoute: typeof EstantesRoute
    }
    '/paginas/$pageId/editar': {
      id: '/paginas/$pageId/editar'
      path: '/editar'
      fullPath: '/paginas/$pageId/editar'
      preLoaderRoute: typeof PaginasPageIdEditarRouteImport
      parentRoute: typeof PaginasPageIdRoute
    }
  }
}

interface EstantesRouteChildren {
  EstantesShelfIdRoute: typeof EstantesShelfIdRoute
}

const EstantesRouteChildren: EstantesRouteChildren = {
  EstantesShelfIdRoute: EstantesShelfIdRoute,
}

const EstantesRouteWithChildren = EstantesRoute._addFileChildren(
  EstantesRouteChildren,
)

interface PaginasPageIdRouteChildren {
  PaginasPageIdEditarRoute: typeof PaginasPageIdEditarRoute
}

const PaginasPageIdRouteChildren: PaginasPageIdRouteChildren = {
  PaginasPageIdEditarRoute: PaginasPageIdEditarRoute,
}

const PaginasPageIdRouteWithChildren = PaginasPageIdRoute._addFileChildren(
  PaginasPageIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  EstantesRoute: EstantesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  LivrosBookIdRoute: LivrosBookIdRoute,
  PaginasPageIdRoute: PaginasPageIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
