/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LivrosIndexRouteImport } from './routes/livros.index'
import { Route as EstantesIndexRouteImport } from './routes/estantes.index'
import { Route as EquipesIndexRouteImport } from './routes/equipes.index'
import { Route as EstantesShelfIdRouteImport } from './routes/estantes.$shelfId'
import { Route as EquipesTeamIdRouteImport } from './routes/equipes.$teamId'
import { Route as PaginasPageIdIndexRouteImport } from './routes/paginas.$pageId.index'
import { Route as LivrosBookIdIndexRouteImport } from './routes/livros.$bookId.index'
import { Route as CapitulosChapterIdIndexRouteImport } from './routes/capitulos.$chapterId.index'
import { Route as PaginasPageIdRevisoesRouteImport } from './routes/paginas.$pageId.revisoes'
import { Route as PaginasPageIdEditarRouteImport } from './routes/paginas.$pageId.editar'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosIndexRoute = LivrosIndexRouteImport.update({
  id: '/livros/',
  path: '/livros/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstantesIndexRoute = EstantesIndexRouteImport.update({
  id: '/estantes/',
  path: '/estantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesIndexRoute = EquipesIndexRouteImport.update({
  id: '/equipes/',
  path: '/equipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstantesShelfIdRoute = EstantesShelfIdRouteImport.update({
  id: '/estantes/$shelfId',
  path: '/estantes/$shelfId',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesTeamIdRoute = EquipesTeamIdRouteImport.update({
  id: '/equipes/$teamId',
  path: '/equipes/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginasPageIdIndexRoute = PaginasPageIdIndexRouteImport.update({
  id: '/paginas/$pageId/',
  path: '/paginas/$pageId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosBookIdIndexRoute = LivrosBookIdIndexRouteImport.update({
  id: '/livros/$bookId/',
  path: '/livros/$bookId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitulosChapterIdIndexRoute = CapitulosChapterIdIndexRouteImport.update({
  id: '/capitulos/$chapterId/',
  path: '/capitulos/$chapterId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginasPageIdRevisoesRoute = PaginasPageIdRevisoesRouteImport.update({
  id: '/paginas/$pageId/revisoes',
  path: '/paginas/$pageId/revisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginasPageIdEditarRoute = PaginasPageIdEditarRouteImport.update({
  id: '/paginas/$pageId/editar',
  path: '/paginas/$pageId/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/equipes/$teamId': typeof EquipesTeamIdRoute
  '/estantes/$shelfId': typeof EstantesShelfIdRoute
  '/equipes/': typeof EquipesIndexRoute
  '/estantes/': typeof EstantesIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/paginas/$pageId/editar': typeof PaginasPageIdEditarRoute
  '/paginas/$pageId/revisoes': typeof PaginasPageIdRevisoesRoute
  '/capitulos/$chapterId/': typeof CapitulosChapterIdIndexRoute
  '/livros/$bookId/': typeof LivrosBookIdIndexRoute
  '/paginas/$pageId/': typeof PaginasPageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/equipes/$teamId': typeof EquipesTeamIdRoute
  '/estantes/$shelfId': typeof EstantesShelfIdRoute
  '/equipes': typeof EquipesIndexRoute
  '/estantes': typeof EstantesIndexRoute
  '/livros': typeof LivrosIndexRoute
  '/paginas/$pageId/editar': typeof PaginasPageIdEditarRoute
  '/paginas/$pageId/revisoes': typeof PaginasPageIdRevisoesRoute
  '/capitulos/$chapterId': typeof CapitulosChapterIdIndexRoute
  '/livros/$bookId': typeof LivrosBookIdIndexRoute
  '/paginas/$pageId': typeof PaginasPageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/equipes/$teamId': typeof EquipesTeamIdRoute
  '/estantes/$shelfId': typeof EstantesShelfIdRoute
  '/equipes/': typeof EquipesIndexRoute
  '/estantes/': typeof EstantesIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/paginas/$pageId/editar': typeof PaginasPageIdEditarRoute
  '/paginas/$pageId/revisoes': typeof PaginasPageIdRevisoesRoute
  '/capitulos/$chapterId/': typeof CapitulosChapterIdIndexRoute
  '/livros/$bookId/': typeof LivrosBookIdIndexRoute
  '/paginas/$pageId/': typeof PaginasPageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/reset-password'
    | '/equipes/$teamId'
    | '/estantes/$shelfId'
    | '/equipes/'
    | '/estantes/'
    | '/livros/'
    | '/paginas/$pageId/editar'
    | '/paginas/$pageId/revisoes'
    | '/capitulos/$chapterId/'
    | '/livros/$bookId/'
    | '/paginas/$pageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/reset-password'
    | '/equipes/$teamId'
    | '/estantes/$shelfId'
    | '/equipes'
    | '/estantes'
    | '/livros'
    | '/paginas/$pageId/editar'
    | '/paginas/$pageId/revisoes'
    | '/capitulos/$chapterId'
    | '/livros/$bookId'
    | '/paginas/$pageId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/busca'
    | '/reset-password'
    | '/equipes/$teamId'
    | '/estantes/$shelfId'
    | '/equipes/'
    | '/estantes/'
    | '/livros/'
    | '/paginas/$pageId/editar'
    | '/paginas/$pageId/revisoes'
    | '/capitulos/$chapterId/'
    | '/livros/$bookId/'
    | '/paginas/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EquipesTeamIdRoute: typeof EquipesTeamIdRoute
  EstantesShelfIdRoute: typeof EstantesShelfIdRoute
  EquipesIndexRoute: typeof EquipesIndexRoute
  EstantesIndexRoute: typeof EstantesIndexRoute
  LivrosIndexRoute: typeof LivrosIndexRoute
  PaginasPageIdEditarRoute: typeof PaginasPageIdEditarRoute
  PaginasPageIdRevisoesRoute: typeof PaginasPageIdRevisoesRoute
  CapitulosChapterIdIndexRoute: typeof CapitulosChapterIdIndexRoute
  LivrosBookIdIndexRoute: typeof LivrosBookIdIndexRoute
  PaginasPageIdIndexRoute: typeof PaginasPageIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/': {
      id: '/livros/'
      path: '/livros'
      fullPath: '/livros/'
      preLoaderRoute: typeof LivrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estantes/': {
      id: '/estantes/'
      path: '/estantes'
      fullPath: '/estantes/'
      preLoaderRoute: typeof EstantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes/': {
      id: '/equipes/'
      path: '/equipes'
      fullPath: '/equipes/'
      preLoaderRoute: typeof EquipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estantes/$shelfId': {
      id: '/estantes/$shelfId'
      path: '/estantes/$shelfId'
      fullPath: '/estantes/$shelfId'
      preLoaderRoute: typeof EstantesShelfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes/$teamId': {
      id: '/equipes/$teamId'
      path: '/equipes/$teamId'
      fullPath: '/equipes/$teamId'
      preLoaderRoute: typeof EquipesTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginas/$pageId/': {
      id: '/paginas/$pageId/'
      path: '/paginas/$pageId'
      fullPath: '/paginas/$pageId/'
      preLoaderRoute: typeof PaginasPageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/$bookId/': {
      id: '/livros/$bookId/'
      path: '/livros/$bookId'
      fullPath: '/livros/$bookId/'
      preLoaderRoute: typeof LivrosBookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capitulos/$chapterId/': {
      id: '/capitulos/$chapterId/'
      path: '/capitulos/$chapterId'
      fullPath: '/capitulos/$chapterId/'
      preLoaderRoute: typeof CapitulosChapterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginas/$pageId/revisoes': {
      id: '/paginas/$pageId/revisoes'
      path: '/paginas/$pageId/revisoes'
      fullPath: '/paginas/$pageId/revisoes'
      preLoaderRoute: typeof PaginasPageIdRevisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginas/$pageId/editar': {
      id: '/paginas/$pageId/editar'
      path: '/paginas/$pageId/editar'
      fullPath: '/paginas/$pageId/editar'
      preLoaderRoute: typeof PaginasPageIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EquipesTeamIdRoute: EquipesTeamIdRoute,
  EstantesShelfIdRoute: EstantesShelfIdRoute,
  EquipesIndexRoute: EquipesIndexRoute,
  EstantesIndexRoute: EstantesIndexRoute,
  LivrosIndexRoute: LivrosIndexRoute,
  PaginasPageIdEditarRoute: PaginasPageIdEditarRoute,
  PaginasPageIdRevisoesRoute: PaginasPageIdRevisoesRoute,
  CapitulosChapterIdIndexRoute: CapitulosChapterIdIndexRoute,
  LivrosBookIdIndexRoute: LivrosBookIdIndexRoute,
  PaginasPageIdIndexRoute: PaginasPageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
