-- ═══════════════════════════════════════════════════════════════════════
-- RH — Seed do efetivo (planilha COLABORADORES.xls — 124 funcionários)
-- Adiciona coluna admissao, limpa entradas antigas e re-insere correto.
-- ═══════════════════════════════════════════════════════════════════════

ALTER TABLE rh.colaboradores ADD COLUMN IF NOT EXISTS admissao date;

-- Apaga entradas anteriores e garante nomes vindos do Excel (sem trailing spaces)
DELETE FROM rh.colaboradores;

INSERT INTO rh.colaboradores (nome, setor, admissao, ativo) VALUES
  ('ADEILSON CUSTODIO GOMES',                   'Montagem',      '2023-12-22', true),
  ('ADEIR PEREIRA DOMINGOS',                    'Almoxarifado',  '2026-04-17', true),
  ('ALESSANDRO LUIZ MARTINS DOS SANTOS',        'Montagem',      '2025-08-22', true),
  ('AMANDA MARIZA FIGUEIREDO DA SILVA',         'Montagem',      '2026-03-09', true),
  ('AMON TALAT FERREIRA E LIMA',                'Metalurgia',    '2020-02-24', true),
  ('ANA CAROLINA GOMES AMORIM',                 'Solda',         '2026-07-02', true),
  ('ANA CAROLINA RAMIRO DA SILVA',              'Montagem',      '2025-03-13', true),
  ('ANA LUIZA BERNARDINO DA SILVA',             'Metalurgia',    '2025-07-16', true),
  ('ANA VITORIA SANTIAGO DOS SANTOS',           'Montagem',      '2025-04-07', true),
  ('ANDREA DE OLIVEIRA',                        'Tratamento',    '2022-08-18', true),
  ('ANDREIZA DIAS DOS SANTOS',                  'Montagem',      '2026-06-01', true),
  ('ANNA FABIA DE SOUZA ARAUJO',               'Montagem',      '2026-02-01', true),
  ('ARILSON SANTANA AZEVEDO',                   'Inspeção',      '2026-02-05', true),
  ('ARTUR FARIA GOMES GUERRA',                  'Administrativo','2022-08-30', true),
  ('AVESTA SHOKRIAN DOS SANTOS',                'Engenharia',    '2022-07-21', true),
  ('BRUNA PEREIRA DA SILVA',                    'Metalurgia',    '2024-12-16', true),
  ('BRUNO HENRIQUE DE SOUZA PERES',             'Solda',         '2026-02-01', true),
  ('CAIO AUGUSTO CALISTO GERMANO',              'Solda',         '2026-06-22', true),
  ('CARLA VERONICA SILVA DE JESUS',             'Montagem',      '2025-04-07', true),
  ('CARLOS HENRIQUE BARBOSA MARQUES',           'Administrativo','2023-08-18', true),
  ('CLEIDER TEODORO DA SILVA',                  'Montagem',      '2026-02-01', true),
  ('CLEMILSSON ROSA DA SILVA',                  'Solda',         '2024-12-20', true),
  ('DAIANE PINTO DOS SANTOS',                   'Solda',         '2024-04-08', true),
  ('DAIANE SILVA FERREIRA',                     'Metalurgia',    '2022-11-09', true),
  ('DANIEL DOMINGUES MONTEIRO',                 'PCP',           '2026-03-13', true),
  ('DANIELLE ADRIANE DE ALMEIDA',               'PCP',           '2019-04-02', true),
  ('DIANA ESTEFANIA APARECIDA DOS SANTOS',      'Montagem',      '2026-02-01', true),
  ('DIOGO GONCALVES SILVA',                     'Tratamento',    '2026-06-01', true),
  ('DIVA VITORIA ARAUJO OLIVEIRA',              'Solda',         '2026-05-18', true),
  ('DIVINA DO SOCORRO APARECIDA DE SOUZA',      'Limpeza',       '2026-06-01', true),
  ('EFIGENIA PEREIRA DOS SANTOS SILVA',         'Limpeza',       '2026-03-09', true),
  ('ELISIO GREGORIO FERREIRA',                  'Metalurgia',    '2019-06-06', true),
  ('ELVINA MESSIAS DA CRUZ',                    'Almoxarifado',  '2021-10-01', true),
  ('ERICK DEYVISON REIS ANICIO',                'Montagem',      '2025-06-01', true),
  ('ERIK DOUGLAS PEREIRA SANTOS',               'Manutenção',    '2024-04-23', true),
  ('ESTER BARBOSA GOMES',                       'Solda',         '2025-03-20', true),
  ('EVANDO FEITOSA LIRA',                       'Transporte',    '2022-07-22', true),
  ('EXPEDITO DORNELES DOS REIS JUNIOR',         'Transporte',    '2025-07-25', true),
  ('FABRIZIO DE ALMEIDA RODRIGUES',             'Tratamento',    '2026-03-01', true),
  ('FERNANDO VANDERLEI GOMES MENDONÇA',         'Metalurgia',    '2019-06-03', true),
  ('FLAVIANO ANICIO BEGATI',                    'Solda',         '2019-03-14', true),
  ('FLAVIO MARTINS BRITO',                      'Metalurgia',    '2025-05-01', true),
  ('GABRIEL HENRIQUE PEREIRA SILVA',            'Metalurgia',    '2022-05-26', true),
  ('GABRIEL PARREIRA XAVIER DE ASSIS',          'Almoxarifado',  '2026-05-01', true),
  ('GERALDO SIMOES RIBEIRO',                    'Administrativo','2026-05-19', true),
  ('GOUBIAH PABLO DE OLIVEIRA MENDES',          'PCP',           '2025-08-11', true),
  ('GUILHERME HENRIQUE DA SILVA SANTOS',        'Pintura',       '2024-02-26', true),
  ('GUILHERME HENRIQUE MACHADO SOARES',         'Metalurgia',    '2026-02-04', true),
  ('GUILHERME SANTOS VITAL ALMEIDA',            'Solda',         '2026-05-05', true),
  ('GUSTAVO DA CRUZ GONCALVES',                 'Solda',         '2026-07-01', true),
  ('GUSTAVO REZENDE DE SOUZA MATOS',            'Solda',         '2025-09-01', true),
  ('HERZI VALADARES FILHO',                     'Montagem',      '2026-02-01', true),
  ('ISABELA NUNES MARTINS',                     'Pintura',       '2026-05-01', true),
  ('ISABELA VITORIA DE SOUZA',                  'Pintura',       '2026-05-01', true),
  ('ISLENE PEREIRA DOS SANTOS',                 'Montagem',      '2026-03-09', true),
  ('JAISSON JUNIOR DE SOUZA',                   'Tratamento',    '2025-02-15', true),
  ('JAMYLA OLIVEIRA LOURENÇO DA SILVA',         'Montagem',      '2025-03-12', true),
  ('JEAN PIERRE DORNELAS PEREIRA DOS REIS',     'Manutenção',    '2026-06-18', true),
  ('JOAO TOMAZ DOS SANTOS',                     'Solda',         '2024-12-16', true),
  ('JOAO VICTOR DA SILVA RODRIGUES',            'Pintura',       '2024-12-16', true),
  ('JOSE CALIXTO DUARTE',                       'Inspeção',      '2023-03-24', true),
  ('JOSE MACIEL MOREIRA',                       'Qualidade',     '2026-04-20', true),
  ('JOSIAS DE ANDRADE',                         'Manutenção',    '2026-03-01', true),
  ('JOYCE SOARES DE MORAIS RIBEIRO',            'Solda',         '2025-04-07', true),
  ('JUCELIA MARQUES DA SILVA',                  'Montagem',      '2023-12-22', true),
  ('JUCIVAL SAO PEDRO DOS SANTOS',              'Metalurgia',    '2024-02-26', true),
  ('JULIA MARA ARAUJO LIMA',                    'Montagem',      '2026-03-09', true),
  ('JULIA VITORIA LOPES SANTOS SILVA',          'Administrativo','2025-05-01', true),
  ('JULIO CESAR PEREIRA JANUARIO',              'Inspeção',      '2026-02-19', true),
  ('JULYA EMANUELLY RODRIGUES ARAUJO',          'Montagem',      '2025-06-01', true),
  ('KAROLAINE PATRICIA DE PAULA',               'Almoxarifado',  '2021-11-01', true),
  ('KAUA SILVA LEITE',                          'Montagem',      '2025-09-01', true),
  ('KELVEN HENRIQUE SOUZA REIS',                'Pintura',       '2025-09-01', true),
  ('KETLEN ROCHA DIAS',                         'Pintura',       '2026-02-01', true),
  ('KETTELY BEATRIZ DO CARMO',                  'Solda',         '2025-09-01', true),
  ('LARISSA MENDES OLIVEIRA',                   'Solda',         '2024-02-26', true),
  ('LEONARDO DIOGO DA SILVA',                   'Pintura',       '2024-06-12', true),
  ('LUCIANA DIONISIO DE SOUZA',                 'Metalurgia',    '2023-03-10', true),
  ('LUCIMAR LOPES DA COSTA',                    'Montagem',      '2025-08-19', true),
  ('LUDMILA FERRAZ CUSTODIO',                   'Montagem',      '2026-05-01', true),
  ('LUIZ KLEBER ALVES DIAS',                    'Solda',         '2026-02-01', true),
  ('LUIZA LIMA GONCALVES E SILVA',              'Montagem',      '2026-05-01', true),
  ('MARCELO LOPES DUARTE',                      'Montagem',      '2022-08-18', true),
  ('MARCELO RODRIGUES BRITO',                   'PCP',           '2022-11-22', true),
  ('MARCOS ALESSANDRO DE OLIVEIRA',             'Administrativo','2025-12-01', true),
  ('MARIA EDUARDA MAGNO DA SILVA',              'Solda',         '2026-04-02', true),
  ('MARILON ERMELINDO MARTINELE FERREIRA',      'Metalurgia',    '2022-11-09', true),
  ('MARIO HENRIQUE MARTINS RODRIGUES',          'Marcenaria',    '2026-06-08', true),
  ('MARLON BILLY BRAGANÇA FRAGA',              'Metalurgia',    '2020-09-01', true),
  ('MARSELL BRETAS CARVALHO',                   'Solda',         '2022-10-13', true),
  ('MICHAEL DA SILVA BESSA',                    'Montagem',      '2025-09-01', true),
  ('MISAEL MARLEY SIQUEIRA DE SOUZA',           'Protótipo',     '2019-02-01', true),
  ('NATHALIA VIEIRA DA SILVA',                  'Pintura',       '2026-03-01', true),
  ('NATHALIA VITORIA ALVES DA SILVA',           'Montagem',      '2025-03-10', true),
  ('NEIMAR ACACIO BEGATI',                      'Metalurgia',    '2019-02-01', true),
  ('NIVALDO SOARES DE BARROS',                  'Inspeção',      '2021-11-26', true),
  ('NIVEA PAULA DA SILVA',                      'Pintura',       '2026-04-02', true),
  ('PALOMA PRINCESS MALTA E SILVA',             'Solda',         '2025-04-07', true),
  ('PAULO GONCALVES DA SILVA',                  'Montagem',      '2025-08-01', true),
  ('PAULO HENRIQUE DIMAS FLORENTINO',           'Solda',         '2026-02-01', true),
  ('PAULO HENRIQUE INACIO OLIVEIRA',            'Solda',         '2025-04-07', true),
  ('PEDRO HENRIQUE SILVA CAMARGO',              'Pintura',       '2026-03-01', true),
  ('PHELIPE PORTO NUNES',                       'Metalurgia',    '2026-02-24', true),
  ('RAFAEL JUNIO BELAMINO PEREIRA',             'Metalurgia',    '2025-02-01', true),
  ('RAUREY DA COSTA SILVA',                     'Montagem',      '2026-03-16', true),
  ('RICARDO MARTINS SANTIAGO',                  'Administrativo','2026-05-01', true),
  ('ROBERTO FERREIRA DA SILVA',                 'Manutenção',    '2022-07-12', true),
  ('ROBSON GUIMARES OLIVEIRA',                  'Solda',         '2025-08-08', true),
  ('RODRIGO DA CUNHA PEREIRA',                  'Protótipo',     '2024-10-09', true),
  ('RONILSON MARTINS DE BARROS',                'Montagem',      '2026-03-09', true),
  ('ROSA MARIA SILVEIRA PIRES',                 'Administrativo','2019-06-03', true),
  ('RYAN MARCIO SILVERIO OLIVEIRA',             'Manutenção',    '2026-05-06', true),
  ('SAMUEL DUARTE DE OLIVEIRA',                 'Solda',         '2025-03-07', true),
  ('TAIS SANTOS GUIMARAES',                     'Montagem',      '2026-06-01', true),
  ('VALDECI PEREIRA FERNANDES',                 'Transporte',    '2026-02-10', true),
  ('VANESSA DOS SANTOS SOARES',                 'Montagem',      '2024-12-16', true),
  ('VICTORIA LETICIA DE OLIVEIRA',              'Montagem',      '2025-03-13', true),
  ('VINICIOS BARBOSA FELIPE MATOS',             'Montagem',      '2020-02-24', true),
  ('VITOR GABRIEL DE SOUZA CAMPOS',             'Montagem',      '2026-03-09', true),
  ('VITOR RENAN SILVA DA CONCEICAO',            'Engenharia',    '2023-05-10', true),
  ('WAINE RODRIGUES ILDEFONSO SANTOS',          'Administrativo','2024-04-08', true),
  ('WANDERLUCIO LOURENCO DE ARAUJO',            'Solda',         '2026-06-18', true),
  ('WEMERSON DA SILVA NUNES',                   'Protótipo',     '2021-03-17', true),
  ('WISLA CRISTIANE RODRIGUES SOUZA',           'Segurança',     '2024-02-26', true);
